In [1]:
import numpy as np

1. Inizializzazione

In [7]:
# 3 feature in ingresso e 5 neuroni nello strato nascosto
input_dim = 3
hidden_dim = 5

# iniziallizazione dei pesi molto piccoli e diversi (MAI A ZERO)
W = np.random.randn(hidden_dim, input_dim) * 0.01

# definizione di bias
b = np.zeros((hidden_dim, 1))

W, b

(array([[-0.00351583,  0.00813242,  0.00629628],
        [-0.00426484,  0.00412544, -0.01546993],
        [ 0.01555668,  0.00866013,  0.01347938],
        [-0.00218796,  0.00590216, -0.00787199],
        [ 0.00058396, -0.0009317 , -0.00623275]]),
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.]]))

2. Esecuzione del calcolo

In [ ]:
# simulazione dato in ingresso
x = np.random.randn(input_dim, 1)

# calcolo del segnale
z = np.dot(W, x) + b

z

array([[-0.03351268],
       [ 0.03289947],
       [ 0.03611819],
       [-0.01656681],
       [ 0.030329  ]])

In [8]:
# passaggio dei dati in batch
batch_size = 4
X_batch = np.random.randn(batch_size, input_dim)

# calcolo vettorializzato, attenzione a trasformare l'array per la moltiplicazione con la matrice

Z_batch = np.dot(W, X_batch.T) + b

Z_batch

array([[-0.00636624,  0.01252277,  0.00994958,  0.00622001],
       [-0.00559214,  0.0134328 ,  0.00401766, -0.01028938],
       [-0.00322492,  0.00438718, -0.01107391, -0.00608611],
       [-0.00589958,  0.01310879,  0.00411742, -0.00637705],
       [ 0.00016562,  0.00033928, -0.00253875, -0.00555643]])

In [9]:
# generazione dei persi con xavier per il calcolo della varianza corretta in base al numero delle feature

def initialize_xavier(n_in, n_out):
# La formula di Xavier: varianza bilanciata tra input e output
# std = sqrt(2 / (n_in + n_out))\n",
    limit = np.sqrt(2.0 / (n_in + n_out))

# Generiamo pesi con questa specifica scala
    W_x = np.random.randn(n_out, n_in) * limit
    b_x = np.zeros((n_out, 1))

    return W_x, b_x

# Testiamo la nuova inizializzazione
W_new, b_new = initialize_xavier(input_dim, hidden_dim)
print(f"Nuova deviazione standard dei pesi: {np.std(W_new):.4f}")

Nuova deviazione standard dei pesi: 0.3855
